### ISSUE TITLE
Given example app not possible to start?

### ISSUE THREAD

**Issue by nagarajanceg** [cdimascio/express-openapi-validator#209]
Repository cloned and done npm install in both express-open-validator & example directory. Then tried to do npm start at example directory ends up in an error.

```
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'express-openapi-validator'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/nagarajangopal/Documents/node/express-openapi-validator/example/app.js:8:30)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3) 
```

node version: v10.13.0
npm version: 6.4.1

npm ls express-openapi-validator :
properly listed express-openapi-validator@3.6.0

Tried this repo "https://github.com/cdimascio/express-openapi-validator-example" and it properly works to execute the examples. I am wondering why it's not possible to do with newer version and  resulted in error.

**Comment by cdimascio** [comment]
@nagarajanceg thanks for the issue. please pull the latest for fixes. there is also a new [README](https://github.com/cdimascio/express-openapi-validator/blob/master/example/README.md)
