### ISSUE TITLE
TypeError caused when request received on different URL then server URL

### ISSUE THREAD

**Issue by TomHartogs** [cdimascio/express-openapi-validator#218]
When testing my API locally I receive a TypeError when I have another server defined in the openapi spec (the mock server in this case).

Using the option `ignorePaths: true` does not prevent this error. I only seem to be able to get rid of the error by deleting the Servers section from the openapi spec.

The specific error thrown is:
`TypeError: Cannot destructure property 'pathParam' of 'undefined' or 'null'.
    at app.param (C:\Users\tom.hartogs\Conversational\Notification-server\node_modules\express-openapi-validator\dist\index.js:95:44)
    at paramCallback (C:\Users\tom.hartogs\node_modules\express\lib\router\index.js:404:7)
    at param (C:\Users\tom.hartogs\node_modules\express\lib\router\index.js:384:5)
    at Function.process_params (C:\Users\tom.hartogs\node_modules\express\lib\router\index.js:410:3)
    at next (C:\Users\tom.hartogs\node_modules\express\lib\router\index.js:275:10)
    at C:\Users\tom.hartogs\Conversational\Notification-server\node_modules\express-openapi-validator\dist\framework\modded.express.mung.js:56:17
    at Layer.handle [as handle_request] (C:\Users\tom.hartogs\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\tom.hartogs\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\tom.hartogs\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\tom.hartogs\node_modules\express\lib\router\index.js:335:12)`

**Comment by cdimascio** [comment]
@TomHartogs please give v3.6.4. i fixed the destructure issue.
let me know how it goes.
if it solves it great. if not, please provide me more details i.e. a canonical example of your spec and service so that i can repro. thanks!

**Comment by TomHartogs** [comment]
@cdimascio Thank you for the super-fast response! I can indeed confirm that this problem is no longer there in v3.6.4.
