### ISSUE TITLE
Aggregation of allOf not supported - Response validation

### ISSUE THREAD

**Issue by luboskriz** [cdimascio/express-openapi-validator#239]
I am getting the following error when validating response for a /route endpoint (see schema and the response example below)
```
Error: .response should NOT have additional properties, .response should NOT have additional properties
    at ResponseValidator._validate (C:\Code\automation\node_modules\express-openapi-validator\dist\middlewares\openapi.response.validator.js:83:32)
    at C:\Code\automation\node_modules\express-openapi-validator\dist\middlewares\openapi.response.validator.js:27:29
    at ServerResponse.json_hook (C:\Code\automation\node_modules\express-openapi-validator\dist\framework\modded.express.mung.js:35:24)
    at ServerResponse.send (C:\Code\automation\node_modules\express\lib\response.js:158:21)
    at c:\Code\automation\src\dataserver\Server.ts:268:25
    at Layer.handle [as handle_request] (C:\Code\automation\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Code\automation\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Code\automation\node_modules\express\lib\router\route.js:112:3)
``` 
**Expected result:** The validation should pass

### Example 1 - Demonstrates the issue
Having the following schema, the below response causes validation error - no additional properties
Schema:
```
---
  openapi: "3.0.0"
  info:
    title: "Test for allOf"
    version: "1"
  paths:
    /route:
      get:
        responses:
          200:
            description: ""
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/RouteType"
  components:
    schemas:
      RouteType:
        allOf:
          -
            $ref: "#/components/schemas/Type1"
          -
            $ref: "#/components/schemas/Type2"
      Type1:
        type: "object"
        additionalProperties: false
        properties:
          property1:
            type: "integer"
      Type2:
        type: "object"
        additionalProperties: false
        properties:
          property2:
            type: "string"
```
Response:
```
---
  property1: 1
  property2: SomeString
```

### Example 2 - No issue

If there is just one item in allOf collection, it validates correctly:

Schema:
```
---
  openapi: "3.0.0"
  info:
    title: "Test for allOf"
    version: "1"
  paths:
    /route:
      get:
        responses:
          200:
            description: ""
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/RouteType"
  components:
    schemas:
      RouteType:
        allOf:
          -
            $ref: "#/components/schemas/Type1"
      Type1:
        type: "object"
        additionalProperties: false
        properties:
          property1:
            type: "integer"
```
Response:
```
---
  property1: 1
```

**Comment by cdimascio** [comment]
thanks will have a look. currently, response validation is not quite as robust as request validation. this certainly needs to be improved.

**Comment by cdimascio** [comment]
@luboskriz thanks for the issue. i'll have a look. it's possible that this is related to https://github.com/cdimascio/express-openapi-validator/issues/104

**Comment by luboskriz** [comment]
Hi @cdimascio I am happy that you will look at the issue! 

I am working on a larger rapidly growing project and this is a no go blocker for us. I tried couple workarounds, but none of them works for me completely. 

I would need to have this fixed as soon as possible, so if it is not a priority for you and you could give me some hints, I would like to help fixing it, even though I am not definitely such expert as you are. I have already tried, but the code took me to the ajv internals and this was too much for me. 

Thanks for any help! I appreciate your work, I really like the library overall.

**Comment by cdimascio** [comment]
@luboskriz this issue occurs for both request and response validation. it's an issue in AJV itself. The arguably its how JSON Schema works
see the thread here https://github.com/epoberezkin/ajv/issues/837

All in all, a workaround is to remove `additonalProperties: false`

**Comment by luboskriz** [comment]
Thanks for the investigation, @cdimascio, appreciate it. I will implement some workaround.

**Comment by cdimascio** [comment]
FYI, u saw this today, [json-schema-merge-all-off](https://github.com/mokkabonna/json-schema-merge-allof). I will plan to look into it. Im curious it might help this situation. If so, perhaps I can leverage it within this lib

**Comment by asafMasa** [comment]
@cdimascio is there any progress with this issue?

**Comment by AlekseyMko** [comment]
Still facing this issue

**Comment by patricktyndall** [comment]
Seeing this issue as well. 

Our API schema is "composed" by combining lower level types into high level complex response types (using `allOf`), and this bug kills all our plans to use this library to help validate responses.

Anybody found a good workaround?

**Comment by SakerGT** [comment]
Also encountering this issue.  Just wondering if there has been any progress?

The `allOf` in OpenAPI does not appear to work the way same as JSON Schema - or at least there seem to be multiple ways in which `allOf` in OpenAPI is interpreted.  Other frameworks/validators seem to enable the composing of multiple Schema objects, even with `additionalProperties: false`.

Below is another example that uses `allOf` to combine schemas with `additionalProperties: false` on the combination, but fails validation of the following scenarios:
- Supplying both `fooName` and `barValue` returns "request/body must not have additional properties"
- Suppling only `fooName` returns "request/body must have required property 'barValue'"
- Supplying only 'barValue` returns "request/body must have required property 'fooName'"

So basically it appears that the composition using `allOf` mentioned in OpenAPI isn't supported, or at least has a problem with `additionalProperties: false`.

```
openapi: 3.0.3
info:
  title: example
  description: allOf example
  version: 0.1.0
servers:
  - url: 'https://example.com'
security:
  - basicSecurity: []
paths:
  '/foo':
    get:
      summary: Summary
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Full"
    post:
      operationId: create_object
      summary: create an object
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Full"
      responses:
        '201':
          description: Created OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: string
components:
  schemas:
    Foo:
      type: object
      properties: 
        fooName: 
          type: string
      required:
        - fooName
    Bar:
      type: object
      properties: 
        barValue: 
          type: string
      required:
        - barValue
    Full:
      description: Full
      allOf:
        - $ref: "#/components/schemas/Foo"
        - $ref: "#/components/schemas/Bar"
      additionalProperties: false
  securitySchemes:
    basicSecurity:
      type: http
      scheme: basic
```
