### ISSUE TITLE
validation error even if format declared in unknownFormats

### ISSUE THREAD

**Issue by hpl002** [cdimascio/express-openapi-validator#290]
**Describe the bug**
Title says it. Trying to verify schema with custom format. Error is thrown even if the format name is included in unknownFormats array.

**To Reproduce**
run with supplied .yaml

**Actual behavior** 
See error output

**Expected behavior**
No errors, rest of schema is valid

**Examples and context**

**YAML:**
```
servers:
  - url: http://localhost:3010/api
    description: Sandbox
openapi: "3.0.0"
info:
  title: Example API
  description: example
  version: v1
  contact:
    email: examle@example.com
tags:
  - name: Account Service
paths:
  /get-should-have-no-body:
    uuid: accounts
    get:
      tags:
        - Account Service
      summary: get without a schema
      responses:
        "200":
          description: OK

```
**ERROR:**
```

error: openapi.validator: Validating schema
error: openapi.validator: validation errors [
  {
    "keyword": "additionalProperties",
    "dataPath": ".paths['/get-should-have-no-body']",
    "schemaPath": "#/additionalProperties",
    "params": {
      "additionalProperty": "uuid"
    },
    "message": "should NOT have additional properties"
  }
]
error: openapi.validator: Validating schema
error: openapi.validator: validation errors [
  {
    "keyword": "additionalProperties",
    "dataPath": ".paths['/get-should-have-no-body']",
    "schemaPath": "#/additionalProperties",
    "params": {
      "additionalProperty": "uuid"
    },
    "message": "should NOT have additional properties"
  }
]
error: (node:11795) UnhandledPromiseRejectionWarning: Error: openapi.validator: args.apiDoc was invalid.  See the output.
    at OpenAPIFramework.initialize (removedPath/node_modules/express-openapi-validator/dist/framework/index.js:31:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async OpenApiSpecLoader.discoverRoutes (removedPath/node_modules/express-openapi-validator/dist/framework/openapi.spec.loader.js:46:39)
error: (node:11795) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
error: (node:11795) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.



```

**JS**
```
        new OpenApiValidator({
          apiSpec: apiGatewayConfigurator._configPath,
          validateResponses: false, // <-- to validate responses
          unknownFormats: ["uuid"], // <-- to provide custom formats
        }).install(app);
```

**Comment by hpl002** [comment]
Please reopen. 

Closed too quickly. Assumed i read the documentation wrong, but seemingly not so.
Have also tried by providing a options object as specified in https://github.com/cdimascio/express-openapi-validator#openapivalidator-options but to no avail.

Would appreciate some clarification or the direction to a verified example..

**Comment by cdimascio** [comment]
@hpl002  Note the error: `Error: openapi.validator: args.apiDoc was invalid.  See the output.` This seems to indicate that your spec is invalid
First, validate your spec to ensure it's syntactically correct. A tool like [swagger editor](https://editor.swagger.io/) can help

**Comment by hpl002** [comment]
The spec is fine. To verify i tried the following:
```
servers:
  - url: http://localhost:3010/api
    description: Sandbox
openapi: "3.0.0"
info:
  title: Example API
  description: example
  version: v1
  contact:
    email: examle@example.com
tags:
  - name: Account Service
paths:
  /someNewPathName:
    uuid: accounts
    get:
      tags:
        - Account Service
      summary: get without a schema
      responses:
        "200":
          description: OK

```
**Note:** here i changed pathName to something without dashes( - ). Swagger editor only throws an error because i have not prefixed they custom keyword with _x-_, which is exactly the problem that _unknownFormats_ solves? Am i misunderstanding?

Using properly prefixed custom extensions throws yet another error (However, this format would be 100% correct according to official swagger spec. This i have verified.)
Following format:
```
(servers:
  - url: http://localhost:3010/api
    description: Sandbox
openapi: "3.0.0"
info:
  title: Example API
  description: example
  version: v1
  contact:
    email: examle@example.com
tags:
  - name: Account Service
paths:
  /someNewPathName:
    x-uuid: accounts
    get:
      tags:
        - Account Service
      summary: get without a schema
      responses:
        "200":
          description: OK)
 
```
Throws:
```
error: (node:13223) UnhandledPromiseRejectionWarning: TypeError: Cannot create property 'parameters' on string 'accounts'
    at Object.visitApi (removedPath/server/node_modules/express-openapi-validator/dist/framework/openapi.spec.loader.js:61:47)
    at OpenAPIFramework.initialize (removedPath/server/node_modules/express-openapi-validator/dist/framework/index.js:40:21)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async OpenApiSpecLoader.discoverRoutes (removedPath/server/node_modules/express-openapi-validator/dist/framework/openapi.spec.loader.js:46:39)
error: (node:13223) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by 
rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://
nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
error: (node:13223) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js proc
ess with a non-zero exit code.
```

**Comment by cdimascio** [comment]
@hpl002 i think you may be misunderstanding the spec. your first example is not valid. you can't  use an arbitrary property e.g. `uuid` directly under a path. in the second example you're effectively declaring a vendor extension. a vendor extension is not a format, and likely not what you want.

here is more information about openapi datatypes:
https://swagger.io/docs/specification/data-models/data-types/


an example using a format 

```
  /user/{userId}:
    get:
      summary: Returns a user by ID.
      parameters:
        - name: userId
          in: path
          required: true
          description: The ID of the user to return.
          schema:
            type: integer
            format: int64 . # <-- that is a known format for the type integer
            minimum: 1

**Comment by hpl002** [comment]
aha! My usage is **completely wrong,** no question about that. 

However, what i'm trying to achieve is seemingly still not supported.
**Are vendor extension supported on path level?** They are allowed according to the [spec](https://swagger.io/docs/specification/openapi-extensions/)

```
Extensions are supported on the root level of the API spec and in the following places:

    info section
    paths section, individual paths and operations
    operation parameters
    responses
    tags
    security schemes
```


They work perfectly fine on operator level.

For reference: 
x-vendorExtension1 breaks
x-vendorExtension2 does not

```
servers:
  - url: http://localhost:3010/api
    description: Sandbox
openapi: "3.0.0"
info:
  title: Example API
  description: example
  version: v1
  contact:
    email: examle@example.com
tags:
  - name: Account Service
paths:
  /someNewPathName:
    x-vendorExtension1: accounts
    get:
      x-vendorExtension2: accounts
      tags:
        - Account Service
      summary: get without a schema
      responses:
        "200":
          description: OK
```

**Comment by cdimascio** [comment]
fixed the issue with vendor extension declared in path. see `v3.12.9`

**Comment by hpl002** [comment]
Great! 🥇 👏 

Appreciate the swift support!
