### ISSUE TITLE
Erroneously getting 'Bad Request: request should have required property 'headers'' error

### ISSUE THREAD

**Issue by nkhil** [cdimascio/express-openapi-validator#516]
**Describe the bug**
i'm building an API in NodeJS. I've got an openapispec (see below) that doesn't throw any errors when validated using editor.swagger.io. It works as expected on localhost. However, after deploying the API on Heroku,  I get the following mysterious error: 

```
Bad Request: request should have required property 'headers'
2021-01-14T01:56:41.458079+00:00 app[web.1]:     at Object.GET-/liveness-not_provided (/app/node_modules/express-openapi-validator/dist/middlewares/openapi.request.validator.js:92:31)
2021-01-14T01:56:41.458079+00:00 app[web.1]:     at RequestValidator.validate (/app/node_modules/express-openapi-validator/dist/middlewares/openapi.request.validator.js:51:41)
2021-01-14T01:56:41.458080+00:00 app[web.1]:     at requestValidationHandler (/app/node_modules/express-openapi-validator/dist/index.js:144:79)
2021-01-14T01:56:41.458081+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2021-01-14T01:56:41.458082+00:00 app[web.1]:     at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
2021-01-14T01:56:41.458083+00:00 app[web.1]:     at /app/node_modules/express/lib/router/index.js:284:7
2021-01-14T01:56:41.458083+00:00 app[web.1]:     at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
2021-01-14T01:56:41.458084+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/index.js:275:10)
2021-01-14T01:56:41.458084+00:00 app[web.1]:     at /app/node_modules/express-openapi-validator/dist/middlewares/openapi.security.js:36:20
2021-01-14T01:56:41.458084+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2021-01-14T01:56:41.458085+00:00 app[web.1]:     at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
2021-01-14T01:56:41.458085+00:00 app[web.1]:     at /app/node_modules/express/lib/router/index.js:284:7
2021-01-14T01:56:41.458085+00:00 app[web.1]:     at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
2021-01-14T01:56:41.458086+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/index.js:275:10)
2021-01-14T01:56:41.458086+00:00 app[web.1]:     at /app/node_modules/express-openapi-validator/dist/middlewares/openapi.multipart.js:53:13
2021-01-14T01:56:41.458086+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2021-01-14T01:56:41.461323+00:00 heroku[router]: at=info method=GET path="/liveness" host=leaderboardapi.herokuapp.com request_id=16016bde-c8e1-4ef0-a726-5cb06c64cd15 fwd="95.147.33.99" dyno=web.1 connect=1ms service=18ms status=400 bytes=416 protocol=https

```

**To Reproduce**
Here's my API definition that doesn't throw up any errors

```yml
openapi: 3.0.0
info:
  title: Leaderboard API
  description: A simple leaderboard API that helps manage teams, games and players.
  version: 1.0.0
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /liveness:
    get:
      description: Returns the readiness of the service
      operationId: ping
      x-eov-operation-id: ping
      x-eov-operation-handler: healthcheck
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: string
                    example: OK
        "401":
          $ref: "#/components/responses/401"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
  /token:
    get:
      security:
        - verifyApiKey: []
      description: Get auth token
      operationId: generateToken
      x-eov-operation-id: generateToken
      x-eov-operation-handler: token
      parameters:
        - $ref: "#/components/parameters/apiKey"
        - $ref: "#/components/parameters/clientId"
        - $ref: "#/components/parameters/clientSecret"
      responses:
        "200":
          description: auth token response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/getTokenResponse"
        "401":
          $ref: "#/components/responses/401"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
  /team:
    post:
      security:
        - bearerAuth: []
      description: Create a new team
      operationId: createTeam
      x-eov-operation-id: createTeam
      x-eov-operation-handler: team
      requestBody:
        description: team schema
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/postTeamSchema"
      responses:
        "201":
          description: Team created successfully
        "401":
          $ref: "#/components/responses/401"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
  /team/{teamId}:
    get:
      description: Get your team info
      operationId: getTeam
      x-eov-operation-id: getTeam
      x-eov-operation-handler: team
      security:
        - verifyApiKey: []
      parameters:
        - in: path
          name: teamId
          schema:
            type: integer
          required: true
          description: Numeric ID of the team to delete
      responses:
        "200":
          description: team info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/getTeamsResponse"
        "401":
          $ref: "#/components/responses/401"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
    delete:
      description: deleteTeam
      operationId: deleteTeam
      x-eov-operation-id: deleteTeam
      x-eov-operation-handler: team
      parameters:
        - in: path
          name: teamId
          schema:
            type: integer
          required: true
          description: Numeric ID of the team to delete
      responses:
        "201":
          description: Successful DELETE response
        "401":
          $ref: "#/components/responses/401"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
    put:
      description: put team
      operationId: putTeam
      x-eov-operation-id: putTeam
      x-eov-operation-handler: team
      parameters:
        - in: path
          name: teamId
          schema:
            type: integer
          required: true
          description: Numeric ID of the team to get
      responses:
        "200":
          description: Successful PUT response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/putTeamResponse"
        "401":
          $ref: "#/components/responses/401"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
  /user/{userId}:
    get:
      description: Get all the users for a team
      operationId: getUser
      x-eov-operation-id: getUser
      x-eov-operation-handler: user
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
          description: Numeric ID of the user
      responses:
        "200":
          description: A list of users
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/userSchema"
        "401":
          $ref: "#/components/responses/401"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
  /users:
    post:
      description: Create a new user
      operationId: createUser
      x-eov-operation-id: createUser
      x-eov-operation-handler: user
      requestBody:
        description: user schema
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/postUserSchema"
      responses:
        "201":
          description: OK
        "401":
          $ref: "#/components/responses/401"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
  /sign-s3:
    get:
      description: get signed Url
      operationId: getS3SignedUrl
      x-eov-operation-id: getS3SignedUrl
      x-eov-operation-handler: s3
      parameters:
        - in: query
          name: filename
          schema:
            type: string
          allowReserved: true
          description: File name
        - in: query
          name: filetype
          schema:
            type: string
          allowReserved: true
          description: File type
      responses:
        "200":
          description: A list of users
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/getS3SignedUrlResponse"
        "401":
          $ref: "#/components/responses/401"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
  /account:
    get:
      description: Account
      operationId: getAccount
      x-eov-operation-id: getAccount
      x-eov-operation-handler: account
      responses:
        "200":
          description: account page
          content:
            text/html:
              schema:
                type: string
        "401":
          $ref: "#/components/responses/401"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
components:
  securitySchemes:
    verifyApiKey:
      type: apiKey
      in: header
      name: x-api-key
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    "401":
      description: Unauthorised Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/UnauthorisedError"
    "404":
      description: Not Found Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/NotFoundError"
    "500":
      description: Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/InternalServerError"
    default:
      description: Invalid Request Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/InvalidRequestError"
  parameters:
    x-team-id:
      name: x-team-id
      description: team id for an existing team
      in: header
      required: true
      schema:
        type: string
    x-correlation-id:
      name: x-correlation-id
      required: true
      in: header
      description: Correlation ID required for log tracing.
      schema:
        type: string
        format: uuid
    apiKey:
      name: x-api-key
      required: true
      in: header
      description: api key
      schema:
        type: string
        additionalProperties: false
    clientId:
      name: x-client-id
      required: true
      description: API user ID
      in: header
      schema:
        type: string
    clientSecret:
      name: x-client-secret
      required: true
      description: API user secret
      in: header
      schema:
        type: string
    teamName:
      name: teamId
      in: query
      required: true
      schema:
        type: string
        example: Team America
  schemas:
    getTokenResponse:
      description: Get token response
      type: object
      additionalProperties: false
      required:
        - authToken
      properties:
        authToken:
          type: string
    getS3SignedUrlResponse:
      description: S3 signed URL response
      type: object
      additionalProperties: false
      required:
        - signedRequest
        - url
      properties:
        signedRequest:
          type: string
        url:
          type: string
    getApiKeyResponse:
      description: new api key response
      type: object
      properties:
        apiKey:
          type: string
          pattern: '[a-zA-Z0-9\b]{32}$' # This is set in constants
    getTeamsResponse:
      $ref: "#/components/schemas/teamSchema"
    postTeamSchema:
      description: team schema
      type: object
      additionalProperties: false
      required:
        - teamName
      properties:
        teamName:
          type: string
    putTeamResponse:
      $ref: "#/components/schemas/teamSchema"
    teamSchema:
      description: team schema
      type: object
      properties:
        teamName:
          type: string
        teamId:
          type: string
    postUserSchema:
      description: user schema
      type: array
      items:
        type: object
        required:
          - firstName
          - lastName
          - email
        properties:
          firstName:
            type: string
          lastName:
            type: string
          email:
            type: string
          teamName:
            type: string
            nullable: true
    userSchema:
      description: user schema
      type: object
      properties:
        userId:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        teamName:
          type: string
    healthCheckResponse:
      description: healthcheck OK response
      type: object
      properties:
        message:
          type: string
          enum:
            - OK
    NotFoundError:
      title: Not Found Error
      additionalProperties: false
      required:
        - message
        - details
      properties:
        message:
          type: string
        details:
          type: string
    UnauthorisedError:
      title: Not Found Error
      additionalProperties: false
      required:
        - message
        - details
      properties:
        message:
          type: string
        details:
          type: string
    InvalidRequestError:
      additionalProperties: false
      required:
        - message
        - details
      properties:
        message:
          type: string
        details:
          type: string
    InternalServerError:
      title: Internal Server Error
      required:
        - message
        - details
      properties:
        message:
          type: string
        details:
          type: string

```

**Actual behavior** 
I get a `Bad Request: request should have required property 'headers'` error when trying to request `GET /liveness`, which is a simple route that doesn't require any headers or query strings. This works as expected locally, but doesn't work when deployed on Heroku.

**Expected behavior**
I shouldn't see the `Bad Request: request should have required property 'headers'` error message, or I should be able to see a more useful error message.

**Examples and context**
Another detail I found was that my request seems to be going into the `validateSecurity` handlers (I have a few logs in that middleware), but it ends abruptly with the `Bad Request: request should have required property 'headers'` error.

Here's my index.js file if it's useful: 

```javascript
const express = require('express');
const cors = require('cors');
const path = require('path');
const { OpenApiValidator } = require('express-openapi-validator');
const config = require('./config');
const database = require('./lib/database')
const middleware = require('./middleware')

const app = express()
app.set('views', './src/views')
app.use(express.static('./public'))
app.engine('html', require('ejs').renderFile)
const apiSpec = path.join(__dirname, `../openapi/openapi.yml`)

app.use(cors())
app.use(express.json())
app.use(express.urlencoded({ extended: false }));

(async function init() {
  await database.connect();
  await new OpenApiValidator({
    apiSpec,
    validateResponses: true,
    operationHandlers: path.join(__dirname, './handlers'),
    validateSecurity: {
      handlers: {
        verifyApiKey(req, scopes) {
          return middleware.verifyApiKey(req)
        },
        bearerAuth(req, scopes) {
          return middleware.verifyToken(req)
        }
      },
    },
  }).install(app)

  app.use((err, _, res) => {
    res.status(err.status || 500).json({
      message: err.message,
      errors: err.errors,
    });
  });

  app.listen(config.port, () => console.log(`Listening on ${config.port}`))
})();
```

**Comment by nkhil** [comment]
I was using version 3.x.x.

Upgrading to 4.x.x seems to have solved this problem. Closing this now!

Thanks for maintaining this library!

**Comment by cdimascio** [comment]
Fantastic!

**Comment by zachweinberg** [comment]
Does anyone know how we can fix this without updating to 4.x.x?

**Comment by kevindavee** [comment]
This problem occurred for Node 15 as well. I downgraded my Node.js to version 10 and the problem disappeared.

**Comment by cdimascio** [comment]
It will be helpful to have a canonical example spec that demonstrates the issue. Feel free to post here or share via a github repo
