### ISSUE TITLE
koa bug on 4.12.0-beta.xx

### ISSUE THREAD

**Issue by damianobarbati** [cdimascio/express-openapi-validator#522]
I have an endpoint accepting both json and urlencoded body with same schema (spec is openapi 3.x validated).

I am trying to enable the validating middleware on specific endpoints because there are paths which are not defined in the spec (ie: healthcheck, docs) and must be excluded from spec validation.

```js
import openapiValidator from 'koa-openapi-validator';

const openapiValidate = openapiValidator.middleware({
    apiSpec: './docs/openapi.json',
});

// apply middleware on this route
router.all("/auth/createToken", openapiValidate, ctx => ....);
```

The spec relevant part is:
```
 *       requestBody:
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/createTokenInput'
 *           application/x-www-form-urlencoded:
 *             schema:
 *               $ref: '#/components/schemas/createTokenInput'
```

Sending a request either as one of supported type:
```
curl http://localhost/auth/createToken -d 'email=xxx' -d 'password=xxx'
curl http://localhost/auth/createToken -H 'Content-type: application/json' -d '{"email":"xxx","password":"xxx"}'
```

I get this error:
```bash 
Bad Request: request should have required property 'body'
at Object.POST-/auth/createToken-application/json (/Users/my-project/node_modules/express-openapi-validator/dist/middlewares/openapi.request.validator.js:104:31)
at RequestValidator.validate (/Users/my-project/node_modules/express-openapi-validator/dist/middlewares/openapi.request.validator.js:40:41)
at /Users/my-project/node_modules/express-openapi-validator/dist/openapi.validator.js:229:53
at /Users/my-project/node_modules/express-openapi-validator/dist/openapi.validator.js:162:28
```

I'm unable to provide a full working repro, but I was hoping you have some idea.

Feel free to close if repro is mandatory.

**Comment by cdimascio** [comment]
@damianobarbati thanks for the issue. i will have a look. 
if you're able to provide a canonical code snippet. that will certainly help us.

**Comment by cdimascio** [comment]
@damianobarbati this is fixed in `v4.12.0-beta.3`
you also need to ensure to use your favority bodyParser e.g. `koa-bodyparser` or `koa-body`

I've updated the [README](https://github.com/cdimascio/express-openapi-validator/tree/lerna-fastify/packages/koa-openapi-validator) to reflect this

**Comment by cdimascio** [comment]
@damianobarbati how is it going with the koa-openapi-validator beta?
i'm interested to get your feedback...
- is it working well?
- have you run into any other issues?

i look forward to hearing you. thanks!

**Comment by damianobarbati** [comment]
@cdimascio unfortunately not:
```js
router.all("/auth/createToken", ctx => ....);
router.all("/auth/createToken", openapiValidate, ctx => ....);
```

The former works, the latter does not. 

I tried both single and multiple accepted content-types for body:
## single accepted content-type
```js
 *       requestBody:
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/createTokenInput'
```
and
```js
 *       requestBody:
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/createTokenInput'
 *           application/x-www-form-urlencoded:
 *             schema:
 *               $ref: '#/components/schemas/createTokenInput'
```

But I get:
```bash
Bad Request: request should have required property 'body'
    at Object.POST-/auth/createToken-application/json (/Users/damians/Desktop/tos-api-reloaded/node_modules/express-openapi-validator/dist/middlewares/openapi.request.validator.js:104:31)
    at RequestValidator.validate (/Users/damians/Desktop/tos-api-reloaded/node_modules/express-openapi-validator/dist/middlewares/openapi.request.validator.js:40:41)
    at /Users/damians/Desktop/tos-api-reloaded/node_modules/express-openapi-validator/dist/openapi.validator.js:229:53
    at /Users/damians/Desktop/tos-api-reloaded/node_modules/express-openapi-validator/dist/openapi.validator.js:162:28
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  status: 400,
  path: '/auth/createToken',
  errors: [
    {
      path: '.body',
      message: "should have required property 'body'",
      errorCode: 'required.openapi.validation'
    }
  ]
}
```

I have koa-body in place, without the validator middleware everything works fine: could it be a wrong initialization?

**Comment by cdimascio** [comment]
@damianobarbati 
Could u modify this [example](https://github.com/cdimascio/express-openapi-validator/tree/lerna-fastify/examples/10-koa-standard) demonstrate your error. I'd like tj get this resolved for u quickly

**Comment by damianobarbati** [comment]
@cdimascio I tried your example and it's giving the same error:

NB: koa-bodyparser is missing in the package.json of example dir

```bash
git clone git@github.com:cdimascio/express-openapi-validator.git
git checkout lerna-fastify
cd examples/10-koa-standard
yarn add koa-bodyparser
node index.js

# another tab
curl localhost:1234/v1/pets -H 'x-api-key: 123' -H 'Content-type:application/json' -d "{}"
```

Results in:
```bash
{"message":"request should have required property 'body'","errors":[{"path":".body","message":"should have required property 'body'","errorCode":"required.openapi.validation"}]}
```

**Comment by cdimascio** [comment]
hi @damianobarbati,
thanks for describing you steps in detail
i notice that you missed a couple steps. 
(i have a hunch that you're not using the latest beta version)

please try the following (it should work). let me know your result. thanks!

```shell
git clone git@github.com:cdimascio/express-openapi-validator.git
cd express-openapi-validator
git checkout lerna-fastify
cd examples/10-koa-standard
lerna bootstrap && lerna run compile
node index.js
```

in another tab
```shell
curl localhost:1234/v1/pets -H 'x-api-key: 123' -H 'Content-type:application/json' -d "{}"
 
{"message":"request.body should have required property 'name', request.body should have required property 'type'","errors":[{"path":".body.name","message":"should have required property 'name'","errorCode":"required.openapi.validation"},{"path":".body.type","message":"should have required property 'type'","errorCode":"required.openapi.validation"}]}%
```

Note: for this test I'm using:
```
node --version
v14.9.0
```

**Comment by cdimascio** [comment]
Note: for this test I'm using:
```
node --version
v14.9.0
```

**Comment by cdimascio** [comment]
hello @damianobarbati 

please try the following (it should work)

```shell
git clone git@github.com:cdimascio/express-openapi-validator.git
cd express-openapi-validator
git checkout lerna-fastify
cd examples/10-koa-standard
lerna bootstrap && lerna run compile
node index.js
```

in another tab

```shell
{
  "message": "request.body should have required property 'name', request.body should have required property 'type'",
  "errors": [
    {
      "path": ".body.name",
      "message": "should have required property 'name'",
      "errorCode": "required.openapi.validation"
    },
    {
      "path": ".body.type",
      "message": "should have required property 'type'",
      "errorCode": "required.openapi.validation"
    }
  ]
}
```

Notice this is the correct behavior. It noting the `name` and `type` are missing

Note: 
I used Node 14 for this test

```shell
node --version
v14.9.0
```

**Comment by cdimascio** [comment]
@damianobarbati 
I ran the test above with the published version and it failed.

apologies, the published version didn't include the latest, i just published a new version beta.4 with the latest

please try it. it should work

```shell
npm install koa-openapi-validator@4.12.0-beta.4
```

please let me know your result.
thanks!

**Comment by cdimascio** [comment]
I verified that this works 

```
mkdir koa-openapi-validator-example
cd koa-openapi-validator-example
npm init -y
npm install koa koa-router koa-bodyparser koa-openapi-validator@4.12.0-beta.4
## copy index.js from 10-koa-standard example into the new package
cp ../express-openapi-validator/examples/10-koa-standard/index.js . 

cp ../express-openapi-validator/examples/10-koa-standard/openapi.yaml . 
```

**Comment by damianobarbati** [comment]
@cdimascio it seems to work, thanks! I'll in dig into details more this week to see if everything is working good.
