### ISSUE TITLE
`Error: schema is invalid` when calling `middleware` multiple times

### ISSUE THREAD

**Issue by ahilke** [cdimascio/express-openapi-validator#535]
**Describe the bug**

I am using `express-openapi-validator` 4.10.11 together with NestJS. In my jest tests, I instantiate the app for every test case. While the first test case passes, following tests fail with the following error:

```
Error: schema is invalid: data.properties['params'].required should NOT have duplicate items (items ## 1 and 0 are identical)
    at Ajv.validateSchema (/workdir/nestjs-with-express-openapi-validator/node_modules/ajv/lib/ajv.js:178:16)
    at Ajv._addSchema (/workdir/nestjs-with-express-openapi-validator/node_modules/ajv/lib/ajv.js:307:10)
    at Ajv.compile (/workdir/nestjs-with-express-openapi-validator/node_modules/ajv/lib/ajv.js:113:24)
    at new Validator (/workdir/nestjs-with-express-openapi-validator/node_modules/express-openapi-validator/dist/middlewares/openapi.request.validator.js:171:45)
    at RequestValidator.buildMiddleware (/workdir/nestjs-with-express-openapi-validator/node_modules/express-openapi-validator/dist/middlewares/openapi.request.validator.js:50:27)
    at RequestValidator.validate (/workdir/nestjs-with-express-openapi-validator/node_modules/express-openapi-validator/dist/middlewares/openapi.request.validator.js:38:37)
    at /workdir/nestjs-with-express-openapi-validator/node_modules/express-openapi-validator/dist/openapi.validator.js:207:53
    at /workdir/nestjs-with-express-openapi-validator/node_modules/express-openapi-validator/dist/openapi.validator.js:142:28
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at /workdir/nestjs-with-express-openapi-validator/node_modules/@nestjs/core/router/router-proxy.js:9:17
```

**To Reproduce**

I reproduced the bug here: https://github.com/ahilke/nestjs-with-express-openapi-validator/tree/reproduce-express-openapi-validator-bug

To reproduce:
- `npm ci`
- `npm run build`
- `npm run test`

**Actual behavior** 

Second call to `middleware` fails with above error.

**Expected behavior**

Second call to `middleware` behaves the same as the first.

**Examples and context**

Some preliminary findings:

1. The bug seems to only happen when passing an object as `apiSpec`. When loading from a file, it seems to behave correctly.

2. I traced the bug to this line: https://github.com/cdimascio/express-openapi-validator/blob/v4.10.11/src/middlewares/openapi.request.validator.ts#L251.
On the first call, `parametersSchema` looks like this:
```
{
  query: {},
  headers: {},
  params: {
    type: 'object',
    properties: { value: [Object] },
    required: [ 'value' ]
  },
  cookies: {}
}
```
On the second call, `parametersSchema` looks like this:
```
{
  query: {},
  headers: {},
  params: {
    type: 'object',
    properties: { value: [Object] },
    required: [ 'value', 'value' ]
  },
  cookies: {}
}
```

**Comment by cdimascio** [comment]
@ahilke thanks. Will look into this. This could be resolved by using a set when adding the property values during the preprocess phase i.e. the code unreferenced.

Feel free to submit a PR. Also, a quick, temporary work around may be to deepClone the spec JSON for the second instantiation of the middleware
