### ISSUE TITLE
Unknown format -- format: ^\d{4}-\d{2}-\d{2}$

### ISSUE THREAD

**Issue by kutenai** [cdimascio/express-openapi-validator#536]
**Describe the bug**
I have been using openapi-validator for some time. I tried updating from an older version and found that at version 4.10+, I started getting an error. The error output is:

```
info: Express server running {"service":"user-service","timestamp":"2021-02-12T03:57:16.693Z"}
(node:68706) UnhandledPromiseRejectionWarning: Error: unknown format "^\d{4}-\d{2}-\d{2}$" is used in schema at path "#/properties/estimatedArrival"
    at Object.generate_format [as code] (/Volumes/sharpertool/proj/peigenesis/peigenesis-api-server/node_modules/ajv/lib/dotjs/format.js:69:15)
    at Object.generate_validate [as validate] (/Volumes/sharpertool/proj/peigenesis/peigenesis-api-server/node_modules/ajv/lib/dotjs/validate.js:374:35)
    at Object.generate_properties [as code] (/Volumes/sharpertool/proj/peigenesis/peigenesis-api-server/node_modules/ajv/lib/dotjs/properties.js:201:26)
    at generate_validate (/Volumes/sharpertool/proj/peigenesis/peigenesis-api-server/node_modules/ajv/lib/dotjs/validate.js:374:35)
    at localCompile (/Volumes/sharpertool/proj/peigenesis/peigenesis-api-server/node_modules/ajv/lib/compile/index.js:88:22)
    at Ajv.compile (/Volumes/sharpertool/proj/peigenesis/peigenesis-api-server/node_modules/ajv/lib/compile/index.js:55:13)
    at Ajv._compile (/Volumes/sharpertool/proj/peigenesis/peigenesis-api-server/node_modules/ajv/lib/ajv.js:348:27)
    at Ajv.getSchema (/Volumes/sharpertool/proj/peigenesis/peigenesis-api-server/node_modules/ajv/lib/ajv.js:204:54)
    at SchemaPreprocessor.resolveSchema (/Volumes/sharpertool/proj/peigenesis/peigenesis-api-server/node_modules/express-openapi-validator/dist/middlewares/parsers/schema.preprocessor.js:323:41)
    at SchemaPreprocessor.extractResponseSchemaNodes (/Volumes/sharpertool/proj/peigenesis/peigenesis-api-server/node_modules/express-openapi-validator/dist/middlewares/parsers/schema.preprocessor.js:300:41)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:68706) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

A portion of the .yaml specification that contains that format is here:
```
          format: ^\d{4}-\d{2}-\d{2}$
```

**To Reproduce**
Parse this .yaml file

```
---
openapi: 3.0.3
info:
  title: Client API
  description: API for access by external web server
  license:
    name: Apache 2.0
  version: 1.0.1
paths:
  /alive:
    get:
      summary: Ping the server and get a simple response
      description: |
        API Endpoint for testing the server connection status
      operationId: aliveGET
      responses:
        "200":
          description: Valid response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AliveResponse'
        "503":
          description: System is unavailable at this time
        "500":
          description: Connection error, or other unhandled situation
      x-swagger-router-controller: Default
      x-eov-operation-handler: controllers/DefaultHandlers
      x-codegen-request-body-name: body
components:
  schemas:
    AliveResponse:
      type: object
      properties:
        connection:
          type: string
          default: Ok
          enum:
          - Ok
          - Failed
        guaranteedTimeOfDay:
          type: string
          format: ^\d{4}-\d{2}-\d{2}$
```

**Actual behavior** 
The code emits this error when starting the express server:

```
info: Express server running {"service":"user-service","timestamp":"2021-02-12T03:57:16.693Z"}
(node:68706) UnhandledPromiseRejectionWarning: Error: unknown format "^\d{4}-\d{2}-\d{2}$" is used in schema at path "#/properties/estimatedArrival"
    at Object.generate_format [as code] (/Volumes/sharpertool/proj/peigenesis/peigenesis-api-server/node_modules/ajv/lib/dotjs/format.js:69:15)
    at Object.generate_validate [as validate] (/Volumes/sharpertool/proj/peigenesis/peigenesis-api-server/node_modules/ajv/lib/dotjs/validate.js:374:35)
    at Object.generate_properties [as code] (/Volumes/sharpertool/proj/peigenesis/peigenesis-api-server/node_modules/ajv/lib/dotjs/properties.js:201:26)
    at generate_validate (/Volumes/sharpertool/proj/peigenesis/peigenesis-api-server/node_modules/ajv/lib/dotjs/validate.js:374:35)
    at localCompile (/Volumes/sharpertool/proj/peigenesis/peigenesis-api-server/node_modules/ajv/lib/compile/index.js:88:22)
    at Ajv.compile (/Volumes/sharpertool/proj/peigenesis/peigenesis-api-server/node_modules/ajv/lib/compile/index.js:55:13)
    at Ajv._compile (/Volumes/sharpertool/proj/peigenesis/peigenesis-api-server/node_modules/ajv/lib/ajv.js:348:27)
    at Ajv.getSchema (/Volumes/sharpertool/proj/peigenesis/peigenesis-api-server/node_modules/ajv/lib/ajv.js:204:54)
    at SchemaPreprocessor.resolveSchema (/Volumes/sharpertool/proj/peigenesis/peigenesis-api-server/node_modules/express-openapi-validator/dist/middlewares/parsers/schema.preprocessor.js:323:41)
    at SchemaPreprocessor.extractResponseSchemaNodes (/Volumes/sharpertool/proj/peigenesis/peigenesis-api-server/node_modules/express-openapi-validator/dist/middlewares/parsers/schema.preprocessor.js:300:41)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:68706) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**Expected behavior**
Well, I think the format is valid, so it should parse it.

**Examples and context**
Oh, see above

**Comment by cdimascio** [comment]
@kutenai tl/dr use `pattern` not `format`

You need a small change to your spec to correct the issue

Use `pattern` e.g.

```yaml
  type: string
  pattern: ^\\d{4}-\\d{2}-\\d{2}$
```

instead of `format`

```yaml
  type: string
  format: ^\\d{4}-\\d{2}-\\d{2}$
```

You can learn more about `format` vs `pattern` [here](https://swagger.io/docs/specification/data-models/data-types/)
