### ISSUE TITLE
Express res.json() returns wrong date when using open-api-validator!

### ISSUE THREAD

**Issue by babaliaris** [cdimascio/express-openapi-validator#589]
**Describe the bug**
When you return a JSON response that contains a date object created by an [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601) string, and in the API spec (.yaml) the date field is type **Date**, you get the wrong **YYYY-MM-DD** back! For example, if the date was created using **"1996-01-03T22:00:00.000Z"** then in the response you get **1996-01-03** instead of  **1996-01-04** which is the correct **YYYY-MM-DD** representation of that UTC date. This only happens if you are using the open-api-validator, else what you get back is the actual ISO-8601 **"1996-01-03T22:00:00.000Z"**. It seems like the open-api-validator cuts the string to only keep the first 10 characters.

1) Just use the following example to test it out. You will see that the response returns **1996-01-03** as the date. 

2) Now disable the open-api-validator middleware by commenting it out. What you will get as a response will be  **"1996-01-03T22:00:00.000Z"* which of course is not the right format but it's definitely the correct DateTime!!!

**Examples and context**
```javascript
const express   = require("express");
const validator = require("express-openapi-validator");

//Create Express APP.
const app = express();

//JSON Middleware.
app.use(express.json());


//Open API Validator Middleware.
app.use(
    validator.middleware({
      apiSpec           : './api.yaml',
      validateRequests  : true,
      validateResponses : true
    })
);



//GET /user
app.get("/user", (req, res)=>
{
    const user = {
        id  : 0,
        name: "John",
        date: new Date("1996-01-03T22:00:00.000Z")
    };

    res.status(200).json(user);
});



//Open API ERROR handler.
app.use((err, req, res, next) => {
    
    res.status(err.status || 500).json({
      message: err.message,
      errors: err.errors,
    });
});


//Start Listening.
app.listen(1996, ()=>
{
    console.log("Listening!!!!");
});
```

```yaml
openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/babaliaris/test/1.0.0
  - description: My Computer
    url: http://localhost:1996
info:
  description: This is a simple API
  version: "1.0.0"
  title: Simple Inventory API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

paths:
  /user:
    get:
      tags:
        - Users
      summary: get user.
      operationId: getUser
      responses:
        
        '200':
          description: Get the json user data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: Something went wrong.

components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
        - date
      properties:
        id:
          type: integer
        name:
          type: string
        date:
          type: string
          format: date
```

**Comment by cdimascio** [comment]
@babaliaris thanks. You are correct. It's not hanging the date probably. Here is the offending [line](
https://github.com/cdimascio/express-openapi-validator/blob/master/src/framework/base.serdes.ts#L16)
Would u be willing to post a PR with the fix?

**Comment by babaliaris** [comment]
Oh I see it! Indeed it splits the ISO string and keeps the first part. Yes I will create a PR, I'd be happy to contribute to this awesome project!

**Comment by babaliaris** [comment]
By the way, I just forked the repo, cloned it, and installed dependencies and some of the tests fail (I didn't touch anything yet). I run the ```npm run test:windows``` script since I'm on a Windows machine:
```bash
1) multi-spec
       "before all" hook for "create campaign should return 200":
     Uncaught Error: listen EADDRINUSE: address already in use :::3000
      at Server.setupListenHandle [as _listen2] (net.js:1318:16)
      at listenInCluster (net.js:1366:12)
      at Server.listen (net.js:1452:7)
      at createServer (test\multi.spec.spec.ts:60:10)
      at Context.<anonymous> (test\multi.spec.spec.ts:9:11)
      at processImmediate (internal/timers.js:461:21)

  2) multi-spec
       "before all" hook for "create campaign should return 200":
     Error: done() called multiple times in hook <multi-spec "before all" hook for "create campaign should return 200"> of file A:\NodeProjects\express-openapi-validator\test\multi.spec.spec.ts
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  3) a multipart request
       that is malformed or not defined
         should throw 405 get method not allowed:
     Error: write ECONNABORTED
      at afterWriteDispatched (internal/stream_base_commons.js:156:25)
      at writeGeneric (internal/stream_base_commons.js:147:3)
      at Socket._writeGeneric (net.js:785:11)
      at Socket._write (net.js:797:8)
      at doWrite (internal/streams/writable.js:377:12)
      at clearBuffer (internal/streams/writable.js:529:7)
      at Socket.Writable.uncork (internal/streams/writable.js:317:7)
      at ClientRequest.end (_http_outgoing.js:828:17)
      at Transform.onend (internal/streams/readable.js:684:10)
      at Transform.EventEmitter.emit (domain.js:467:12)
      at endReadableNT (internal/streams/readable.js:1327:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)

  4) security.defaults
       "before all" hook for "should return 404 for undocumented route when using Router":
     Uncaught Error: listen EADDRINUSE: address already in use :::3000
      at Server.setupListenHandle [as _listen2] (net.js:1318:16)
      at listenInCluster (net.js:1366:12)
      at Server.listen (net.js:1452:7)
      at Function.listen (node_modules\express\lib\application.js:618:24)
      at Context.<anonymous> (test\router.spec.ts:41:18)
      at processImmediate (internal/timers.js:461:21)

  5) security.defaults
       "before all" hook for "should return 404 for undocumented route when using Router":
     Error: done() called multiple times in hook <security.defaults "before all" hook for "should return 404 for undocumented route when using Router"> of file A:\NodeProjects\express-openapi-validator\test\router.spec.ts
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)



npm ERR! code ELIFECYCLE
npm ERR! errno 5
npm ERR! express-openapi-validator@4.12.8 test:windows: `set TS_NODE_FILES=true & mocha -r source-map-support/register -r ts-node/register  --files --recursive test/**/*.spec.ts`
npm ERR! Exit status 5
npm ERR!
npm ERR! Failed at the express-openapi-validator@4.12.8 test:windows script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\babaliaris\AppData\Roaming\npm-cache\_logs\2021-04-27T14_00_56_477Z-debug.log
```
