### ISSUE TITLE
Path alises using `$ref` not working

### ISSUE THREAD

**Issue by jfoclpf** [cdimascio/express-openapi-validator#758]
**Describe the bug**
Path alises using `$ref` not working

**To Reproduce**

File openapi.yaml has this portion:
```yaml
  /municipios/{municipio}:
    summary: Detalhes sobre Município  
    get:
      parameters:
        - in: path
          name: municipio
          required: true
          schema:
            type: string
            example: évora
          allowReserved: true
          description: Município
        - $ref: '#/components/parameters/json'
      responses:
        '200':
          description: Detalhes do Município
          content:
            application/json:
              schema:
                type: string

  /municipio/{municipio}:
    $ref: '#/paths/~1municipios~1{municipio}'
```

Path `/municipio/{municipio}` is an alias of `/municipios/{municipio}`

**Actual behavior** 

```
  geoapipt:server TypeError: Cannot convert undefined or null to object
  geoapipt:server     at Function.keys (<anonymous>)
  geoapipt:server     at SchemaPreprocessor.gatherSchemaNodesFromPaths (/home/joao/dev/geoapi.pt/node_modules/express-openapi-validator/dist/middlewares/parsers/schema.preprocessor.js:79:41)
  geoapipt:server     at SchemaPreprocessor.preProcess (/home/joao/dev/geoapi.pt/node_modules/express-openapi-validator/dist/middlewares/parsers/schema.preprocessor.js:46:24)
  geoapipt:server     at /home/joao/dev/geoapi.pt/node_modules/express-openapi-validator/dist/openapi.validator.js:86:95 +0ms
  geoapipt:server html +0ms
```

**Expected behavior**
No error upon GET `/municipio/{municipio}` or GET `/municipios/{municipio}`

**Comment by jfoclpf** [comment]
Considering that `$ref: '#/components/parameters/json'` was already working, my guess is that this validator does not consider `~1` as valid escapes for `/`

Nonetheless documentation refers:

<h3 id="escape" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0.5rem; font-family: &quot;Open Sans&quot;, sans-serif; font-weight: 500; line-height: 2.5rem; color: rgb(33, 37, 41); font-size: 1.625rem; letter-spacing: 0.01em; -webkit-font-smoothing: antialiased; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Escape Characters</h3><code style="box-sizing: border-box; font-family: &quot;Roboto Mono&quot;, monospace; font-size: 14px; color: rgb(232, 62, 140); overflow-wrap: break-word; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">/</code><span style="color: rgb(33, 37, 41); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"><span> </span>and<span> </span></span><code style="box-sizing: border-box; font-family: &quot;Roboto Mono&quot;, monospace; font-size: 14px; color: rgb(232, 62, 140); overflow-wrap: break-word; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">~</code><span style="color: rgb(33, 37, 41); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"><span> </span>are special characters in JSON Pointers, and need to be escaped when used literally (for example, in path names).</span>

Character | Escape With
-- | --
~ | ~0
/ | ~1

<br class="Apple-interchange-newline">
