### ISSUE TITLE
Issue with Default Handler in resolver

### ISSUE THREAD

**Issue by kesha-shah** [cdimascio/express-openapi-validator#844]
**Describe the bug**
With [this](https://github.com/cdimascio/express-openapi-validator/pull/675/files) commit, there is one issue caused which is blocking us to use default exported functions in APIs

**To Reproduce**
1. Use any version > 4.13.2 - This bug got introduced in version 4.13.4
2. Create one HTTP API function, export it as  default function, set it as `operationId` and set its path in `x-eov-operation-handler`
3. Try to invoke that API
4. 
**Actual behavior** 
It gives error `Route.get() requires a callback function but got a [object Object]`
Stacktrace : `Route.get() requires a callback function but got a [object Object]\n    at Route.<computed> [as get] (/Users/keshashah/work/api-framework/node_modules/express/lib/router/route.js:211:15)\n    at Function.proto.<computed> [as get] (/Users/keshashah/work/api-framework/node_modules/express/lib/router/index.js:521:19)\n    at OpenApiValidator.installOperationHandlers (/Users/keshashah/work/api-framework/node_modules/express-openapi-validator/src/openapi.validator.ts:314:37)\n    at /Users/keshashah/work/api-framework/node_modules/express-openapi-validator/src/openapi.validator.ts:215:30\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","timestamp":"2023-05-18T06:02:49.057Z","type":"app-log"}`

**Expected behavior**
It should return JSON or any expected response. 

**Examples and context**
This bug got created because of this `    const handler = tmpModules[modulePath][oId] || tmpModules[modulePath].default;
`
here in default it should take handler from `tmpModules[modulePath].default[oId]` instead of returning direct `tmpModules[modulePath].default`

Please let me know if I can create PR to fix this issue.

**Comment by kesha-shah** [comment]
Proposed PR : https://github.com/cdimascio/express-openapi-validator/pull/846
