### ISSUE TITLE
Cannot read security of undefined

### ISSUE THREAD

**Issue by LadIQe** [cdimascio/express-openapi-validator#88]
Hi,

Im trying to make it work, but Im getting this error

```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'security' of undefined
starter-node-documentation       |     at /usr/app/node_modules/express-openapi-validator/dist/middlewares/openapi.security.js:16:47
starter-node-documentation       |     at Layer.handle [as handle_request] (/usr/app/node_modules/express/lib/router/layer.js:95:5)
starter-node-documentation       |     at trim_prefix (/usr/app/node_modules/express/lib/router/index.js:317:13)
starter-node-documentation       |     at /usr/app/node_modules/express/lib/router/index.js:284:7
starter-node-documentation       |     at Function.process_params (/usr/app/node_modules/express/lib/router/index.js:335:12)
starter-node-documentation       |     at next (/usr/app/node_modules/express/lib/router/index.js:275:10)
starter-node-documentation       |     at /usr/app/node_modules/express-openapi-validator/dist/middlewares/openapi.multipart.js:37:13
starter-node-documentation       |     at Layer.handle [as handle_request] (/usr/app/node_modules/express/lib/router/layer.js:95:5)
starter-node-documentation       |     at trim_prefix (/usr/app/node_modules/express/lib/router/index.js:317:13)
starter-node-documentation       |     at /usr/app/node_modules/express/lib/router/index.js:284:7
```

Im using node, docker, express etc.

Here is my code:
```
// some code above
const documentation = require('./components/documentation')
// some code below

new OpenApiValidator({
  apiSpec: documentation,
  validateResponses: true
}).install(app)
```

documentation is JSON object. According to error, which is pointing on row 16, it looks like problem is here:
`const securities = req.openapi.schema.security || context.apiDoc.security;`

I tried to add security[] to my documentation, but it doesnt work, so I assume problem is req.openapi.schema.scurity. To makes it clear, my app has 2 backends, one is for app, which is used by FE (there are all routes like get/post/...), second one is for OpenAPI documentation (we are using swagger-ui-express, nothing for production, thats why validator is here) which is using first one, where are all routes.

My questions is: its something with validator or where validator is using (BE for OpenAPI - no production)

Thank you :)

**Comment by cdimascio** [comment]
@LadIQe, thanks for the issue. I will have a look. Would you mind outputting the content of documentation here, so I can reproduce. Thanks!

**Comment by LadIQe** [comment]
Code is splitted into smaller parts for better readability, so we are using module.exports in js files. 

Here is file with documentation code. Its just part of it. Hope you understand.
[doc.txt](https://github.com/cdimascio/express-openapi-validator/files/3767421/doc.txt)

**Comment by cdimascio** [comment]
did a super quick test with `GET /todos`
Note that i inlined the entire doc i.e. the contents of doc.txt

This seems to work for `GET /todos`
Does that endpoint work for you?
If so perhaps the issue is with the documentation snipped you posted above. 
Will do a bit more digging, but wanted to provide this information in case it helps to reveal something more

```javascript
const express = require('express');
const path = require('path');
const cookieParser = require('cookie-parser');
const bodyParser = require('body-parser');
const logger = require('morgan');
const http = require('http');
const OpenApiValidator = require('../../src').OpenApiValidator;
const app = express();

app.use(bodyParser.urlencoded());
app.use(bodyParser.text());
app.use(bodyParser.json());
app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));
const spec = path.join(__dirname, 'openapi.yaml');
app.use('/spec', express.static(spec));

const apiSpec = {
  openapi: '3.0.1',
  info: {
    version: '0.1.0',
    title: 'Test OpenAPI',
    description: 'API documentation',
  },
  servers: [
    {
      url: 'https://localhost:3000/',
      description: 'Local server',
    },
  ],
  tags: [
    {
      name: 'Todo',
      description:
        'Get all todos stored in database. Get one todo by provided id. Create or update todo with given data -WIP',
    },
  ],
  paths: {
    '/todos': {
      get: {
        tags: ['Todo'],
        description: 'Get todos',
        operationId: 'getTodos',
        security: [
          {
            bearerAuth: [],
          },
        ],
        parameters: [
          {
            name: 'sortBy',
            in: 'query',
            schema: {
              $ref: '#/components/schemas/sortBy',
            },
            required: true,
          },
          {
            name: 'sortDirection',
            in: 'query',
            schema: {
              $ref: '#/components/schemas/sortDirection',
            },
          },
          {
            name: 'limit',
            in: 'query',
            schema: {
              $ref: '#/components/schemas/number',
            },
            required: true,
          },
          {
            name: 'offset',
            in: 'query',
            schema: {
              $ref: '#/components/schemas/offset',
            },
            required: false,
          },
        ],
        responses: {
          '200': {
            description: 'Todos were obtained',
            content: {
              'application/json': {
                schema: {
                  $ref: '#/components/schemas/Todos',
                },
                example: {
                  entities: {
                    todos: {
                      1: {
                        id: 1,
                        text: 'repair damaged car',
                        done: false,
                      },
                      2: {
                        id: 2,
                        text: 'buy new house',
                        done: true,
                      },
                      3: {
                        id: 3,
                        text: 'get to the moon',
                        done: false,
                      },
                    },
                  },
                  result: [1, 2, 3],
                  hasNext: false,
                },
              },
            },
          },
          '400': {
            description: 'Missing parameters',
            content: {
              'application/json': {
                schema: {
                  $ref: '#/components/schemas/Error',
                },
                example: {
                  message: 'Sort by is missing',
                  internal_code: 'missing_parameters',
                },
              },
            },
          },
        },
      },
      post: {
        tags: ['Todo'],
        description: 'Create todo with given data in body',
        operationId: 'createTodo',
        security: [
          {
            bearerAuth: [],
          },
        ],
        requestBody: {
          required: true,
          content: {
            'application/json': {
              schema: {
                $ref: '#/components/schemas/Todo',
              },
              example: {
                text: 'Create new framework',
                done: false,
              },
            },
          },
        },
        responses: {
          '201': {
            description: 'Todo was created',
            content: {
              'application/json': {
                schema: {
                  $ref: '#/components/schemas/Todos',
                },
                example: {
                  entities: {
                    todos: {
                      16: {
                        id: 16,
                        text: 'Create new car brand',
                        done: true,
                      },
                    },
                  },
                  result: [16],
                },
              },
            },
          },
          '400': {
            description: 'Missing parameters',
            content: {
              'application/json': {
                schema: {
                  $ref: '#/components/schemas/Error',
                },
                example: {
                  message: 'Text is missing',
                  internal_code: 'missing_parameters',
                },
              },
            },
          },
        },
      },
    },
    '/todos/{id}': {
      get: {
        tags: ['Todo'],
        description: 'Get todo details by given id',
        operationId: 'getTodo',
        security: [
          {
            bearerAuth: [],
          },
        ],
        parameters: [
          {
            name: 'id',
            in: 'path',
            schema: {
              $ref: '#/components/schemas/number',
            },
            required: true,
          },
        ],
        responses: {
          '200': {
            description: 'Todo was obtained',
            content: {
              'application/json': {
                schema: {
                  $ref: '#/components/schemas/Todos',
                },
                example: {
                  entities: {
                    todos: {
                      5: {
                        id: 5,
                        text: 'buy a cup',
                        done: false,
                      },
                    },
                  },
                  result: [5],
                },
              },
            },
          },
          '400': {
            description: 'Missing parameters',
            content: {
              'application/json': {
                schema: {
                  $ref: '#/components/schemas/Error',
                },
                example: {
                  message: 'Todo id is missing',
                  internal_code: 'missing_parameters',
                },
              },
            },
          },
        },
      },
      put: {
        tags: ['Todo'],
        description: 'Update todo',
        operationId: 'putTodo',
        security: [
          {
            bearerAuth: [],
          },
        ],
        parameters: [
          {
            name: 'id',
            in: 'path',
            schema: {
              $ref: '#/components/schemas/number',
            },
            required: true,
          },
        ],
        requestBody: {
          required: true,
          content: {
            'application/json': {
              schema: {
                $ref: '#/components/schemas/Todo',
              },
              example: {
                done: true,
              },
            },
          },
        },
        responses: {
          '200': {
            description: 'Todo was updated',
            content: {
              'application/json': {
                schema: {
                  $ref: '#/components/schemas/Todos',
                },
                example: {
                  entities: {
                    todos: {
                      15: {
                        id: 15,
                        text: 'get to the jungle',
                        done: true,
                      },
                    },
                  },
                  result: [15],
                },
              },
            },
          },
          '400': {
            description: 'Missing parameters',
            content: {
              'application/json': {
                schema: {
                  $ref: '#/components/schemas/Error',
                },
                example: {
                  message: 'Todo id is missing',
                  internal_code: 'missing_parameters',
                },
              },
            },
          },
        },
      },
      delete: {
        tags: ['Todo'],
        description: 'Delete todo by given id',
        operationId: 'deleteTodo',
        security: [
          {
            bearerAuth: [],
          },
        ],
        parameters: [
          {
            name: 'id',
            in: 'path',
            schema: {
              $ref: '#/components/schemas/number',
            },
            required: true,
          },
        ],
        responses: {
          '200': {
            description: 'Todo was deleted',
          },
          '400': {
            description: 'Missing parameters',
            content: {
              'application/json': {
                schema: {
                  $ref: '#/components/schemas/Error',
                },
                example: {
                  message: 'Id is missing',
                  internal_code: 'missing_parameters',
                },
              },
            },
          },
        },
      },
    },
    '/todos/create': {
      post: {
        tags: ['Todo'],
        description: 'Create todo from admin panel',
        operationId: 'createTodoFromAdmin',
        security: [
          {
            bearerAuth: [],
          },
        ],
        requestBody: {
          required: true,
          content: {
            'application/json': {
              schema: {
                allOf: [
                  {
                    type: 'object',
                    required: ['user_id'],
                    properties: {
                      user_id: {
                        $ref: '#/components/schemas/number',
                      },
                    },
                  },
                  {
                    $ref: '#/components/schemas/Todo',
                  },
                ],
              },
              example: {
                user_id: 1,
                text: 'go to the shop',
                done: false,
              },
            },
          },
        },
        responses: {
          '201': {
            description: 'Todo from admin panel was created',
            content: {
              'application/json': {
                schema: {
                  $ref: '#/components/schemas/Todos',
                },
              },
            },
          },
          '400': {
            description: 'Missing parameters',
            content: {
              'application/json': {
                schema: {
                  $ref: '#/components/schemas/Error',
                },
                example: {
                  message: 'Id is missing',
                  internal_code: 'missing_parameters',
                },
              },
            },
          },
        },
      },
    },
  },
  components: {
    securitySchemes: {
      bearerAuth: {
        type: 'http',
        scheme: 'bearer',
        bearerFormat: 'JWT',
      },
    },
    schemas: {
      number: {
        type: 'integer',
        format: 'int32',
      },
      sortBy: {
        type: 'string',
        default: 'id',
        example: 'name',
      },
      sortDirection: {
        type: 'string',
        enum: ['asc', 'desc', 'ASC', 'DESC'],
        default: 'desc',
        example: 'asc',
      },
      offset: {
        type: 'string',
        default: '',
      },
      arrayOfIntegers: {
        type: 'array',
        items: {
          type: 'integer',
        },
      },
      identificationNumber: {
        type: 'object',
        properties: {
          id: {
            allOf: [
              {
                $ref: '#/components/schemas/number',
              },
              {
                example: 5,
              },
            ],
          },
        },
      },
      text: {
        type: 'string',
        example: 'learn python',
      },
      Error: {
        type: 'object',
        properties: {
          message: {
            type: 'string',
          },
          internal_code: {
            type: 'string',
          },
        },
      },
      Todo: {
        type: 'object',
        required: ['id', 'text'],
        properties: {
          text: {
            $ref: '#/components/schemas/text',
          },
          done: {
            type: 'boolean',
            example: true,
          },
        },
      },
      Todos: {
        type: 'object',
        properties: {
          entities: {
            type: 'object',
            properties: {
              todos: {
                type: 'object',
                properties: {
                  id: {
                    allOf: [
                      {
                        $ref: '#/components/schemas/identificationNumber',
                      },
                      {
                        $ref: '#/components/schemas/Todo',
                      },
                    ],
                  },
                },
              },
            },
          },
          result: {
            $ref: '#/components/schemas/arrayOfIntegers',
          },
          hasNext: {
            type: 'boolean',
          },
        },
      },
    },
  },
};

// 1. Install the OpenApiValidator on your express app
new OpenApiValidator({
  apiSpec,
}).install(app);

// 2. Add routes
app.get('/todos', function(req, res, next) {
  res.json([{ id: 1, name: 'max' }, { id: 2, name: 'mini' }]);
});

// 3. Create a custom error handler
app.use((err, req, res, next) => {
  // format error
  console.error(err, err.stack);
  if (!err.status && !err.errors) {
    res.status(500).json({
      errors: [
        {
          message: err.message,
        },
      ],
    });
  } else {
    res.status(err.status).json({
      message: err.message,
      errors: err.errors,
    });
  }
});

const server = http.createServer(app);
server.listen(3000);
console.log('Listening on port 3000');

module.exports = app;
```

**Comment by cdimascio** [comment]
FYI, if its easier to chat directly, we can use this gitter: https://gitter.im/cdimascio-oss/community

**Comment by LadIQe** [comment]
I signed into gitter so we can talk there ;)

**Comment by LadIQe** [comment]
ok it seems it solved with changing rows order. It looks like swagger ui express was to blame.

My previous code where was problem
```
new OpenApiValidator({
  apiSpec: documentation,
  validateResponses: true,
  securityHandlers: {
    bearerAuth: (req, scopes, schema) => {
      console.log(req, scopes, schema)
    }
  }
}).install(app)

app.use('/', swaggerUi.serve, swaggerUi.setup(documentation))
```

Now when I change order, it works
```
app.use('/', swaggerUi.serve, swaggerUi.setup(documentation))

new OpenApiValidator({
  apiSpec: documentation,
  validateResponses: true,
  securityHandlers: {
    bearerAuth: (req, scopes, schema) => {
      console.log(req, scopes, schema)
    }
  }
}).install(app)
```

So it would be good to make a documentation about it for people who use swagger-ui-express. It can saves them a lot of time

**Comment by cdimascio** [comment]
ideally, yes it should work. if it is not working, i certainly want to get it working for you :)

To make sure i understand where we are currently I'll attempt to summarize:
(let me know if the following is accurate)
- security validation is now working. the solution was to move the swagger ui serve middleware prior to installing the OpenApiValidator
- response validation is returning an error?

assuming, the summary is accurate, what is the error you get on response validation?

**Comment by LadIQe** [comment]
yes, security error was fixed with moving swagger-ui prior to installing validator, so this is fixed. Now when I change response schema in OpenAPI documentation to test, if response validation works, and I execute it in swagger ui, I get no error. I looked into console, if something is there, but console/terminal is clear

As you can see on image below, my response schema is little bit different to test if validation works. But there is no error
<img width="941" alt="Screenshot 2019-10-24 at 17 00 56" src="https://user-images.githubusercontent.com/52506795/67498662-1def9c80-f680-11e9-9ac8-cec098fd5091.png">

**Comment by cdimascio** [comment]
Thanks @LadIQe. I'm going to create a new issue for the response case you pasted above.

**Comment by cdimascio** [comment]
I've added an FAQ section describing how to integrate `swagger-ui-express`
Let me know if you feel more information can be provided to help users with this use case

**Comment by cdimascio** [comment]
Thank you too! Much appreciated
I'll have a look at the response issue soon, though i may not get to it until this weekend.

**Comment by LadIQe** [comment]
Thats absolutely ok :) I appreciate your effort :) thank you very much
