### ISSUE TITLE
express-openapi-validator + @apidevtools/json-schema-ref-parser leads to an error in 5.2.0

### ISSUE THREAD

**Issue by EvgenijHenning** [cdimascio/express-openapi-validator#939]
**Describe the bug**
Since 5.2.0 I'm getting an error with the express-openapi-validator. With the previous 5.1.6 everything was finde. After some digging I could narrow it down to the json-schema-ref-parser.

While the initial loading is fine the validator throws exceptions on any endpoint call. The stack looks like:
```
ReferenceError: location is not defined
    at Object.cwd (/app/node_modules/@apidevtools/json-schema-ref-parser/dist/lib/util/url.js:71:9)
    at $RefParser.parse (/app/node_modules/@apidevtools/json-schema-ref-parser/dist/lib/index.js:101:37)
    at $RefParser.resolve (/app/node_modules/@apidevtools/json-schema-ref-parser/dist/lib/index.js:145:24)
    at $RefParser.bundle (/app/node_modules/@apidevtools/json-schema-ref-parser/dist/lib/index.js:165:24)
    at Object.bundle (/app/node_modules/@apidevtools/json-schema-ref-parser/dist/lib/index.js:160:32)
    at OpenAPIFramework.loadSpec (/app/node_modules/express-openapi-validator/dist/framework/index.js:62:34)
    at OpenAPIFramework.initialize (/app/node_modules/express-openapi-validator/dist/framework/index.js:16:35)
    at OpenApiSpecLoader.discoverRoutes (/app/node_modules/express-openapi-validator/dist/framework/openapi.spec.loader.js:29:60)
    at OpenApiSpecLoader.load (/app/node_modules/express-openapi-validator/dist/framework/openapi.spec.loader.js:21:21)
    at Module.openapiValidator (/app/node_modules/express-openapi-validator/dist/index.js:31:8)
```

**To Reproduce**
I'll try to setup a repo for testing. 

**Actual behavior** 
Starting up the server is fine but as soon as you call a route the exception is thrown.

**Expected behavior**
The bug is only in 5.2.0 and going back to 5.1.6 resolves the issue.

**Examples and context**
This is how I load the openapi.yaml file in
```
...
  const apiSpec = process.cwd() + '/openapi.yaml'
  const apiConfig = YAML.load(apiSpec)
...

  connector(operations, apiConfig, { apiSeparator: '/' })(app)

```

**Comment by vganzin** [comment]
@EvgenijHenning , hi!
Have you solved this problem?

**Comment by cdimascio** [comment]
Can you provide a canonical version of your api spec that can be used to reproduce this issue.

**Comment by EvgenijHenning** [comment]
> @EvgenijHenning , hi! Have you solved this problem?

@vganzin I didn't. I rolled back to the old version and since then I had no time to look further into it.

Thanks for providing an example to reproduce the error.

**Comment by vganzin** [comment]
@cdimascio 
Problem in 
const controllers = path.join(__dirname, 'api/controllers');
operationHandlers: {basePath: controllers}

my tree
-app.js
-api
--controllers
---session.js


in session.js
const sessionController = {
    activate: activate
};
module.exports = sessionController;


full path in my docker container "opt/production/application/app.js

**Comment by vganzin** [comment]
Dear @cdimascio, could you reproduce this problem ?
Thanks
